import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Froge Assistant',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-neutral-900 flex min-h-screen flex-col"`}
      >
        <main className="flex flex-1 flex-col">{children}</main>
      </body>
    </html>
  );
}
